"""add role to users

Revision ID: 03e32e10a243
Revises: 3f75b62ae9be
Create Date: 2026-07-19 13:24:26.085456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e32e10a243'
down_revision: Union[str, Sequence[str], None] = '3f75b62ae9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('CUSTOMER', 'STAFF', 'ADMIN', name='user_role', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
