"""add custom design accept flow

Revision ID: 7869ba83059f
Revises: a6dda29e3429
Create Date: 2026-07-24 00:29:36.128732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7869ba83059f'
down_revision: Union[str, Sequence[str], None] = 'a6dda29e3429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_details', sa.Column('custom_design_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'booking_details', 'custom_designs', ['custom_design_id'], ['id'])
    op.add_column('custom_designs', sa.Column('status', sa.Enum('PENDING', 'PRICED', 'ACCEPTED', 'REJECTED', name='custom_design_status', native_enum=False, length=20), nullable=False, server_default='PENDING'))
    op.alter_column('custom_designs', 'status', server_default=None)
    op.add_column('staff', sa.Column('can_price_custom_designs', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('staff', 'can_price_custom_designs', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'can_price_custom_designs')
    op.drop_column('custom_designs', 'status')
    op.drop_constraint(None, 'booking_details', type_='foreignkey')
    op.drop_column('booking_details', 'custom_design_id')
    # ### end Alembic commands ###
