"""chain staff: nullable home branch, floating, day assignments

Revision ID: b64bebd58e35
Revises: cdc91f0dfb7f
Create Date: 2026-08-01 01:20:49.790177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b64bebd58e35'
down_revision: Union[str, Sequence[str], None] = 'cdc91f0dfb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_day_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('PIN', 'AUTO', name='assignment_source', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'day', name='uq_staff_day')
    )
    op.add_column(
        'staff', sa.Column('floating', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.alter_column('staff', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('staff', 'floating')
    op.drop_table('staff_day_assignments')
    # ### end Alembic commands ###
