"""capability matrix, capacity ledger, allocation runs

Revision ID: cdc91f0dfb7f
Revises: a91f3e07c852
Create Date: 2026-08-01 00:16:27.752965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cdc91f0dfb7f'
down_revision: Union[str, Sequence[str], None] = 'a91f3e07c852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('assigned_count', sa.Integer(), nullable=False),
    sa.Column('unassigned_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'service_id', name='uq_capability_cell')
    )
    op.add_column(
        'booking_details',
        sa.Column('staff_requested', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'services',
        sa.Column('skill_group', sa.String(length=30), nullable=False, server_default='MANI'),
    )
    op.add_column(
        'services',
        sa.Column('body_zone', sa.String(length=10), nullable=False, server_default='HANDS'),
    )
    op.add_column('services', sa.Column('resource', sa.String(length=30), nullable=True))
    op.add_column(
        'services',
        sa.Column(
            'turn_weight', sa.Numeric(precision=4, scale=2), nullable=False, server_default='1.0'
        ),
    )
    op.add_column(
        'services',
        sa.Column('buffer_after_min', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'staff', sa.Column('days_off', sa.String(length=20), nullable=False, server_default='')
    )
    op.add_column(
        'staff', sa.Column('max_hours_week', sa.Integer(), nullable=False, server_default='40')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'max_hours_week')
    op.drop_column('staff', 'days_off')
    op.drop_column('services', 'buffer_after_min')
    op.drop_column('services', 'turn_weight')
    op.drop_column('services', 'resource')
    op.drop_column('services', 'body_zone')
    op.drop_column('services', 'skill_group')
    op.drop_column('booking_details', 'staff_requested')
    op.drop_table('staff_capabilities')
    op.drop_table('allocation_runs')
    # ### end Alembic commands ###
