"""part-time working hours per staff

Revision ID: ef5edb298a8c
Revises: b8d3f1e6c920
Create Date: 2026-08-05 22:36:50.665670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5edb298a8c'
down_revision: Union[str, Sequence[str], None] = 'b8d3f1e6c920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('work_start_hour', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('work_end_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'work_end_hour')
    op.drop_column('staff', 'work_start_hour')
    # ### end Alembic commands ###
